services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on: # starts after db is started
      db:
        condition: service_healthy
  db:
    container_name: postgres
    hostname: ${POSTGRES_HOST}
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_DATA}
#      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    ports:
     - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
