basePath: /api
definitions:
  entity.TaskForDocs:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: it's a simple rest api app that allows you to perform CRUD operations
    on tasks
  title: task_manager API
paths:
  /api/task.json:
    get:
      description: Get tasks or single task by ID, also has pagination
      parameters:
      - default: 1
        description: number of the page
        in: query
        name: page
        type: integer
      - default: 1000
        description: max amount of tasks
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.TaskForDocs'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get tasks
      tags:
      - tasks
  /api/task.json/{id}:
    get:
      description: Get tasks or single task by ID, also has pagination
      parameters:
      - description: task ID
        in: path
        name: id
        type: integer
      - default: 1
        description: number of the page
        in: query
        name: page
        type: integer
      - default: 1000
        description: max amount of tasks
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.TaskForDocs'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get tasks
      tags:
      - tasks
swagger: "2.0"
